Patch to include the Oberbank
nblock/ofxstatement-austrian pull request #4
Opened 2017-03-17 09:50 UTC by statementaustrianoberbank

Warning: This is my first commit, and I am not fluent in Python. I have mainly modified the existing raiffeisen plugin to make it read my Oberbank file.

Problems:
I could not figure out how to tell ofxstatement to delete the first line (which contains the colum names). So if you do not delete the first line with the colum names, you will get an error, similar to the one attached.

I have not modified the test case, so one for Oberbank is still missing.
[error.txt](https://github.com/nblock/ofxstatement-austrian/files/850171/error.txt)

Thanks in advance for looking at this!

2017-03-18 07:57 UTC, nblock requested changes
It would be great to use this file as 'oberbank.csv' sample instead of the sample you provided. Just to avoid copy-paste errors.

However, it contains private data such as IBANs. Would you mind to anonymize those entries and commit this file as 'oberbank.csv'?

2017-03-18 07:57 UTC, nblock commented on src/ofxstatement/plugins/oberbank.py
> +        # Currency
You could use the following snippet to skip the first line:
```
# Skip header line
if self.cur_record == 1:
    return None
```

2017-03-18 08:00 UTC, nblock commented
Thank you very much for your contribution! Once you've updated your commits, tests can be added for the Oberbank plugin.

2017-03-19 12:03 UTC, statementaustrianoberbank commented
I have added the code you suggested to skip the first line and changed the filename for the original file to oberbank.csv. It was already anonymized, so I am not sure if you want me to completely remove the IBAN (it is not mine) or if it can stay.

2017-03-19 14:48 UTC, nblock commented
LGTM, thx for the improvements!
Are you going to provide a test for the plugin or should I take it from there?

2017-03-19 14:50 UTC, nblock approved these changes

2017-03-19 15:19 UTC, statementaustrianoberbank commented
It would be great if you can take it from here, as I have never written a test before and know nothing about the whole process. If you do not have time for this, then I could try to adapt the others so that they fit. Thanks again!

2017-03-19 15:50 UTC, nblock commented
OK, I'll take it from here.

2017-04-08 16:32 UTC, nblock commented
Fixed with 8314e5569bfd673893f71a4fc3f55097ce4ee6fc.

2017-04-08 16:32 UTC, closed without merging